@startuml
!include ./puml.style

autoactivate on

participant "_: Main" as Main
participant "conf: Configuration" as Config
participant "theMatch: Match" as Match


[-> Main: main(args)

    create Config
        Main -> Config: this(args)
    return

    create Match
        Main -> Match: this(conf.str1, conf.str2)
    return

    Main -> Match: play()
        return winner

    return

@enduml